#define RTOS_SYSTEM_PRIORITIES  8
#define RTOS_SYSTEM_PRIORITIES  RTOS_SYSTEM_PRIORITIES-1
#define RTOS_MAX_PRIORITIE      0
#define RTOS_IDLE_TASK_PRIORITY RTOS_SYSTEM_PRIORITIES



void RTOS_init(void);
void RTOS_Start(void);